def get_rna_fastq(wildcards):
    fq_files = list(samples_info.loc[wildcards.sample,['R1_file_path','R2_file_path']])
    return {
        "R1":fq_files[0],
        "R2":fq_files[1],
    }

def get_sample_bed(wildcards):
    bed_file = samples_info.loc[wildcards.sample,'Target_file_bed']
    return(bed_file)

def get_sample_gender(wildcards):
    bed_file = samples_info.loc[wildcards.sample,'gender']
    return(bed_file)


def get_vcf_name(wildcards):
    if wildcards.caller == 'vardict':          
        name =  "--tumor-id " + wildcards.sample + '_T'
    else: 
        name =  "--tumor-id " + wildcards.sample
    return(name)


def get_vcf_file(wildcards):
    if wildcards.sample in paired_samples:
        file_name =  f"results/vcf/" + 'paired' + "/{sample}/{caller}.vcf"
    else:
        file_name =  f"results/vcf/" + 'unpaired' + "/{sample}/{caller}.vcf"
    return(file_name)



##### Modules #####

include: "rules/qc.smk"
include: "rules/mapping.smk"
# include: "rules/isofox.smk"
# include: "rules/calling_paired.smk"
# include: "rules/calling_paired_strelka.smk"
# include: "rules/calling_unpaired.smk"
### call mutation module
include: "rules/call_mut_sentieon.smk"
#include: "rules/merge.smk"
include: "rules/merge_loop.smk"
include: "rules/SV.smk"
include: "rules/SNV.smk"
include: "rules/findvirus.smk"
include: "rules/fusion.smk"