sentieon_call = (
    config.get("softwares", {})
          .get("sentieon", {})
          .get("call", "")
)
### call mutation module
redup = False
if has_executable(sentieon_call):
    print(f"[INFO] Sentieon found: {sentieon_call.strip()}")
    include: "rules/call_mut_sentieon.smk"
else:
    print("[INFO] Sentieon not found or not configured. Using GATK mutation calling rules.")
    include: "rules/call_mut_GATK.smk"

##### Modules #####

include: "rules/qc.smk"
include: "rules/mapping.smk"
#include: "rules/merge.smk"
include: "rules/merge_loop.smk"
include: "rules/SNV.smk"

if genome_version in ['b37','hg38','hg38_chr21']: ## only OK for human
    include: "rules/fusion.smk"
if genome_version in ['b37','hg38']: ## only OK for human
    include: "rules/isofox.smk"