---
output:
  html_document:
    theme: cosmo # darkly
    css: style.css
    toc: false
    code_download: false
    number_sections: true
    pandoc_args:
      - "--shift-heading-level-by=-1"
  rmdformats::material:
    highlight: kate
params:
  ## common config
  af_keygenes: '~/Documents/Project/project_clindet/source/clindet_report/report/test_data/final_panel.tsv'
  genome_version: 'b37'
  title: "Clindet WES analysis case Report"
  tumor_name: "CGGA_1288"
  ## patient and sample info
  patient_csv: '~/Documents/Project/project_clindet/source/clindet_report/report/test_data/patient_info.csv'
  ## Assay QC
  ngs_bit_sample_geneder: '~/Documents/Project/project_clindet/source/clindet_report/report/test_data/ngs-bit/CGGA_528-gender.tsv'
  conpair_contamination: '~/Documents/Project/project_clindet/source/clindet_report/report/test_data/CGGA_1288/CGGA_1288-T_contamination.txt'
  conpair_concordance: '~/Documents/Project/project_clindet/source/clindet_report/report/test_data/CGGA_1288/CGGA_1288-T_concordance.txt'
  ngs_bit_mapqc_tumor: '~/Documents/Project/project_clindet/source/clindet_report/report/test_data/ngs-bit/CGGA_528_T_bamqc.txt'
  ngs_bit_mapqc_normal: '~/Documents/Project/project_clindet/source/clindet_report/report/test_data/ngs-bit/CGGA_528_NC_bamqc.txt'
  
  ## virus reports #######
  virusbreakend_tsv: NULL
  virusbreakend_vcf: NULL
  ## somatic mut MAF ########
  somatic_mut_maf: "~/Documents/Project/project_clindet/source/clindet_report/report/test_data/CGGA_1288.maf"
  ## copy number results ##
  ascat_res_dir: '~/Documents/Project/project_clindet/source/clindet_report/report/test_data/ascat/CGGA_1288'
  purple_res_dir: '~/Documents/Project/project_clindet/source/clindet_report/report/test_data/purple'
  purple_purity: '~/Documents/Project/project_clindet/source/clindet_report/report/test_data/purple/CGGA_1288.purple.purity.tsv'
  purple_qc: '~/Documents/Project/project_clindet/source/clindet_report/report/test_data/purple/CGGA_1288.purple.qc'
  purple_som_cnv: '~/Documents/Project/project_clindet/source/clindet_report/report/test_data/purple/CGGA_1288.purple.cnv.somatic.tsv'
  purple_som_gene_cnv: '~/Documents/Project/project_clindet/source/clindet_report/report/test_data/purple/CGGA_1288.purple.cnv.gene.tsv'
  purple_som_snv_vcf: NULL
  # structural variants results
  sv_available: NULL
  somatic_sv_tsv: NULL
  somatic_sv_vcf: NULL
  
  # softwares environment summary
  conda_list: NULL

description: "Analysis of tumor/normal samples at Clindet"
title: "`r paste(params$tumor_name, params$title)`"
editor_options:
  markdown:
    wrap: 72
---

<style type="text/css">
.main-container {
  max-width: 1400px;
  margin-left: auto;
  margin-right: auto;
}
</style>

```{r knitr_opts, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE, echo = FALSE,
  warning = FALSE, message = FALSE,
  error = TRUE
) # continue running report even after chunk errors

report_dir <- normalizePath(dirname(knitr::current_input()))
knitr::opts_knit$set(
  root.dir = report_dir,
  output.dir = report_dir
)
```

```{r setup, child='sections/00_setup.Rmd'}
```

```{r patient_info, child='sections/01_patient_info.Rmd'}
```


```{r assay_qc, child='sections/02_assay_qc.Rmd'}
```

```{r genomic_snv, child='sections/03_genomic_snv.Rmd'}
```

```{r genomic_cnv, child='sections/03_genomic_cnv.Rmd'}
```

<!-- ```{r annotation, child='sections/04_annotation.Rmd'} -->
<!-- ``` -->

<!-- ```{r actionability, child='sections/05_actionability.Rmd'} -->
<!-- ``` -->

<!-- ```{r summary, child='sections/06_summary.Rmd'} -->
<!-- ``` -->

```{r appendix, child='sections/07_appendix.Rmd'}
```
