resources:
  b37:
    REFFA: "/public/ClinicalExam/lj_sih/projects/project_clindet/resources/ref_genome/b37/Homo_sapiens.GRCh37.GATK.illumina.fasta"
    GENOME_BED: ""
    GTF: "/public/ClinicalExam/lj_sih/projects/project_clindet/resources/ref_genome/b37/Homo_sapiens.GRCh37.87.gtf"
    GFF: "/public/ClinicalExam/lj_sih/projects/project_clindet/resources/ref_genome/b37/Homo_sapiens.GRCh37.87.gff3"
    WES_PON: "/public/ClinicalExam/lj_sih/projects/project_clindet/resources/ref_genome/b37/Mutect2-exome-panel.vcf"
    WES_BED: "/public/ClinicalExam/lj_sih/projects/project_clindet/reference/b37/b37.exon.bed"
    WGS_PON: "/public/ClinicalExam/lj_sih/projects/project_clindet/resources/ref_genome/b37/Mutect2-WGS-panel-b37.vcf"
    DBSNP: "/public/ClinicalExam/lj_sih/projects/project_clindet/resources/ref_genome/b37/Homo_sapiens_assembly19.dbsnp138.vcf"
    DBSNP_GZ: "/public/ClinicalExam/lj_sih/projects/project_clindet/resources/ref_genome/b37/Homo_sapiens_assembly19.dbsnp138.vcf.gz"
    DBSNP_INDEL: "/public/ClinicalExam/lj_sih/projects/project_clindet/resources/ref_genome/b37/Homo_sapiens_assembly19.dbsnp138.indel.vcf.gz"
    MUTECT2_VCF: "/public/ClinicalExam/lj_sih/projects/project_clindet/resources/ref_genome/b37/af-only-gnomad.raw.sites.vcf"
    REFFA_DICT: "/public/ClinicalExam/lj_sih/projects/project_clindet/resources/ref_genome/b37/Homo_sapiens.GRCh37.GATK.illumina.fasta"
    MUTECT2_germline_vcf: "/public/ClinicalExam/lj_sih/projects/project_clindet/resources/ref_genome/b37/af-only-gnomad.raw.sites.vcf"
    common_vcf: "/public/ClinicalExam/lj_sih/projects/project_clindet/resources/ref_genome/b37/00-common_all.vcf.gz"
    RNA_EDIT_VCF: "/public/ClinicalExam/lj_sih/projects/project_clindet/resources/ref_genome/b37/b37.RNAediting.vcf.gz"
  hg19:
    REFFA: "/public/home/lijf/env/genome/broad/hg19/ucsc.hg19.fasta"
    GENOME_BED: "/public/ClinicalExam/lj_sih/resource/genome/human/hg19/genome.bed"
    GTF: "/public/ClinicalExam/lj_sih/resource/genome/human/GRCh37/gencode.v19.annotation.gtf"
    WES_PON: "/public/ClinicalExam/lj_sih/projects/project_clindet/resources/human/hg19/WES/MM_pon.vcf.gz"
    WES_BED: "/public/ClinicalExam/lj_sih/resource/genome/human/hg19/hg19.exon.bed"
    WGS_PON: "/public/ClinicalExam/lj_sih/projects/project_pipeline/WGS/MMWGSPE300_RJ/hg19/results/vcf/paired/PoN_sent/panel_of_normal.vcf.gz"
    DBSNP: "/public/home/lijf/env/genome/broad/hg19/dbsnp_138.hg19.vcf"
    DBSNP_GZ: "/public/ClinicalExam/lj_sih/resource/genome/human/hg19/dbsnp_151.hg19.vcf.gz"
    DBSNP_INDEL: "/public/ClinicalExam/lj_sih/resource/genome/human/hg19/dbsnp_151_indel.hg19.vcf.gz"
    MUTECT2_VCF: "/public/ClinicalExam/lj_sih/resource/af-only-gnomad.raw.sites.hg19.vcf.gz"
    MUTECT2_germline_vcf: "/public/ClinicalExam/lj_sih/resource/af-only-gnomad.raw.sites.hg19.vcf.gz"
    REFFA_DICT: "/public/home/lijf/env/genome/broad/hg19/ucsc.hg19.fasta"
    BED_GENOME: "/public/home/lijf/projects/clinrep/meta/bed/genome/hg19/genome.bed"
    BED_PANEL: "/public/home/lijf/projects/clinrep/meta/bed/panel/hg19_al/IDT-100.Targeted.hg19.bed"
    BED_PANEL_MM: "/public/home/lijf/projects/clinrep/meta/bed/panel/hg19_mm/MM_panel_genes.Targeted.hg19_20211012.final.bed"
    BED_PANEL_EXTEND: "/public/home/lijf/projects/clinrep/meta/bed/panel/hg19_al/IDT-100.Targeted.hg19.extend.bed"
    BED_PANEL_EXTEND_MM: "/public/home/lijf/projects/clinrep/meta/bed/panel/hg19_mm/MM_panel_genes.Targeted.hg19_20211012.final.extend.bed"
    BIAT_PANEL: "/public/home/lijf/projects/clinrep/meta/bed/panel/hg19_al/IDT-100.Targeted.hg19.interval_list"
    BIAT_PANEL_MM: "/public/home/lijf/projects/clinrep/meta/bed/panel/hg19_mm/MM_panel_genes.Targeted.hg19_20211012.final.interval_list"
    common_vcf: "/public/ClinicalExam/lj_sih/resource/genome/human/hg19/00-common_all_hg19.vcf.gz"
  hg38:
    REFFA: "/public/ClinicalExam/lj_sih/projects/project_clindet/resources/ref_genome/hg38/GRCh38_masked_exclusions_alts_hlas.fasta"
    GENOME_BED: ""
    GTF: "/public/ClinicalExam/lj_sih/projects/project_clindet/resources/ref_genome/b37/Homo_sapiens.GRCh37.87.gtf"
    WES_PON: "/public/ClinicalExam/lj_sih/projects/project_clindet/resources/ref_genome/hg38/1000g_pon.hg38.vcf.gz"
    WES_BED: "/public/ClinicalExam/lj_sih/resource/genome/human/hg38/hg38.bed"
    WGS_PON: "/public/ClinicalExam/lj_sih/projects/project_clindet/resources/ref_genome/hg38/1000g_pon.hg38.vcf.gz"
    DBSNP: "/public/ClinicalExam/lj_sih/projects/project_clindet/resources/ref_genome/hg38/dbsnp_138.hg38.vcf.gz"
    DBSNP_GZ: "/public/ClinicalExam/lj_sih/projects/project_clindet/resources/ref_genome/hg38/dbsnp_138.hg38.vcf.gz"
    DBSNP_INDEL: ""
    MUTECT2_VCF: "/public/ClinicalExam/lj_sih/projects/project_clindet/resources/ref_genome/hg38/af-only-gnomad.hg38.vcf.gz"
    REFFA_DICT: "/public/ClinicalExam/lj_sih/projects/project_clindet/resources/ref_genome/hg38/GRCh38_masked_exclusions_alts_hlas.fasta"
    MUTECT2_germline_vcf: "/public/ClinicalExam/lj_sih/projects/project_clindet/resources/ref_genome/hg38/af-only-gnomad.hg38.vcf.gz"
    common_vcf: "/AbsoPath/of/clindet/folder/resources/ref_genome/hg38/00-common_all.vcf.gz"
    RNA_EDIT_VCF: ""
  WBcel235:
    REFFA: "/public/ClinicalExam/lj_sih/projects/project_clindet/resources/ref_genome/WBcel235/WBcel235_genome.fa"
    GTF: "/public/ClinicalExam/lj_sih/projects/project_clindet/resources/ref_genome/WBcel235/Caenorhabditis_elegans.WBcel235.114.gtf"
    GENOME_BED: ""
    DBSNP: ""
    DBSNP_GZ: "/public/ClinicalExam/lj_sih/projects/project_clindet/reference/WBcel235/worm_fake_dbsnp.vcf.gz"
    DBSNP_INDEL: "/public/ClinicalExam/lj_sih/projects/project_clindet/reference/WBcel235/worm_fake_dbsnp.vcf.gz"
    MUTECT2_VCF: "/public/ClinicalExam/lj_sih/projects/project_clindet/reference/WBcel235/c_elegans.dbsnp.vcf.gz"
    WGS_PON: ""
    REFFA_DICT: ""
  hg38_chr21:
    REFFA: "mini_test_data/dna/data/refs/sequence/Homo_sapiens_assembly38_chr21.fasta"
    GENOME_BED: ""
    GTF: ""
    GFF3: ""
    WES_PON: ""
    WES_BED: ""
    WGS_PON: ""
    DBSNP: "mini_test_data/dna/data/refs/annotations/dbsnp_146.hg38_chr21.vcf.gz"
    DBSNP_GZ: "mini_test_data/dna/data/refs/annotations/dbsnp_146.hg38_chr21.vcf.gz"
    DBSNP_INDEL: "mini_test_data/dna/data/refs/annotations/Mills_and_1000G_gold_standard.indels.hg38_chr21.vcf.gz"
    MUTECT2_VCF: "mini_test_data/dna/data/refs/annotations/gnomAD.r2.1.1.GRCh38.PASS.AC.AF.only_chr21.vcf.gz"
    REFFA_DICT: ""
    MUTECT2_germline_vcf: "mini_test_data/dna/data/refs/annotations/gnomAD.r2.1.1.GRCh38.PASS.AC.AF.only_chr21.vcf.gz"
    common_vcf: "mini_test_data/dna/data/refs/annotations/gnomAD.r2.1.1.GRCh38.PASS.AC.AF.only_chr21.vcf.gz"
    RNA_EDIT_VCF: 
  varanno:
    hg19:
      KNOWN_SITES1: "/public/home/lijf/env/genome/broad/hg19/dbsnp_138.hg19.vcf"
      KNOWN_SITES2: "/public/home/lijf/env/genome/broad/hg19/Mills_and_1000G_gold_standard.indels.hg19.sites.vcf"
    b37:
      KNOWN_SITES1: "/public/ClinicalExam/lj_sih/projects/project_clindet/resources/ref_genome/b37/1000G_phase1.snps.high_confidence.b37.vcf.gz"
      KNOWN_SITES2: "/public/ClinicalExam/lj_sih/projects/project_clindet/resources/ref_genome/b37/1000G_phase1.indels.b37.vcf.gz"
    hg38:
      KNOWN_SITES1: "/public/ClinicalExam/lj_sih/projects/project_clindet/resources/ref_genome/hg38/1000G_phase1.snps.high_confidence.hg38.vcf.gz"
      KNOWN_SITES2: "/public/ClinicalExam/lj_sih/projects/project_clindet/resources/ref_genome/hg38/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"
