resources:
  b37:
    REFFA: "resources/ref_genome/b37/Homo_sapiens.GRCh37.GATK.illumina.fasta"
    GENOME_BED: ""
    GTF: "resources/ref_genome/b37/Homo_sapiens.GRCh37.87.gtf"
    GFF: "resources/ref_genome/b37/Homo_sapiens.GRCh37.87.gff3"
    WES_PON: "resources/ref_genome/b37/Mutect2-exome-panel.vcf"
    WES_BED: "reference/b37/b37.exon.bed"
    WGS_PON: "resources/ref_genome/b37/Mutect2-WGS-panel-b37.vcf"
    DBSNP: "resources/ref_genome/b37/Homo_sapiens_assembly19.dbsnp138.vcf"
    DBSNP_GZ: "resources/ref_genome/b37/Homo_sapiens_assembly19.dbsnp138.vcf.gz"
    DBSNP_INDEL: "resources/ref_genome/b37/Homo_sapiens_assembly19.dbsnp138.indel.vcf.gz"
    MUTECT2_VCF: "resources/ref_genome/b37/af-only-gnomad.raw.sites.vcf"
    REFFA_DICT: "resources/ref_genome/b37/Homo_sapiens.GRCh37.GATK.illumina.fasta"
    MUTECT2_germline_vcf: "resources/ref_genome/b37/af-only-gnomad.raw.sites.vcf"
    common_vcf: "resources/ref_genome/b37/00-common_all.vcf.gz"
    RNA_EDIT_VCF: "resources/ref_genome/b37/b37.RNAediting.vcf.gz"
  hg38:
    REFFA: "resources/ref_genome/hg38/GRCh38_masked_exclusions_alts_hlas.fasta"
    GENOME_BED: ""
    GFF: "resources/ref_genome/hg38/Homo_sapiens.GRCh38.115.chr_prefix.gff3"
    GTF: "resources/ref_genome/b37/Homo_sapiens.GRCh37.87.gtf"
    WES_PON: "resources/ref_genome/hg38/1000g_pon.hg38.vcf.gz"
    WES_BED: "/public/ClinicalExam/lj_sih/resource/genome/human/hg38/hg38.bed"
    WGS_PON: "resources/ref_genome/hg38/1000g_pon.hg38.vcf.gz"
    DBSNP: "resources/ref_genome/hg38/dbsnp_138.hg38.vcf.gz"
    DBSNP_GZ: "resources/ref_genome/hg38/dbsnp_138.hg38.vcf.gz"
    DBSNP_INDEL: ""
    MUTECT2_VCF: "resources/ref_genome/hg38/af-only-gnomad.hg38.vcf.gz"
    REFFA_DICT: "resources/ref_genome/hg38/GRCh38_masked_exclusions_alts_hlas.fasta"
    MUTECT2_germline_vcf: "resources/ref_genome/hg38/af-only-gnomad.hg38.vcf.gz"
    common_vcf: "resources/ref_genome/hg38/00-common_all.vcf.gz"
    RNA_EDIT_VCF: ""
  WBcel235:
    REFFA: "resources/ref_genome/WBcel235/WBcel235_genome.fa"
    GTF: "resources/ref_genome/WBcel235/Caenorhabditis_elegans.WBcel235.114.gtf"
    GENOME_BED: ""
    DBSNP: ""
    DBSNP_GZ: "reference/WBcel235/worm_fake_dbsnp.vcf.gz"
    DBSNP_INDEL: "reference/WBcel235/worm_fake_dbsnp.vcf.gz"
    MUTECT2_VCF: "reference/WBcel235/c_elegans.dbsnp.vcf.gz"
    WGS_PON: ""
    REFFA_DICT: ""
  mm10:
    REFFA: []
    GENOME_BED: ""
    GTF: ""
    GFF: ""
    WES_PON: ""
    WES_BED: ""
    WGS_PON: ""
    DBSNP: ""
    DBSNP_GZ: ""
    DBSNP_INDEL: []
    MUTECT2_VCF: ""
    REFFA_DICT: ""
    MUTECT2_germline_vcf: ""
    common_vcf: ""
    RNA_EDIT_VCF: ""
  varanno:
    b37:
      KNOWN_SITES1: "resources/ref_genome/b37/1000G_phase1.snps.high_confidence.b37.vcf.gz"
      KNOWN_SITES2: "resources/ref_genome/b37/1000G_phase1.indels.b37.vcf.gz"
    hg38:
      KNOWN_SITES1: "resources/ref_genome/hg38/1000G_phase1.snps.high_confidence.hg38.vcf.gz"
      KNOWN_SITES2: "resources/ref_genome/hg38/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"
