singularity:
  cgppindel:
    sif: "resources/containers/pindel.sif"
    repo: "docker://quay.io/wtsicgp/cgppindel:3.11.1"
  cgpwgs:
    sif: "resources/containers/cgpwgs.sif"
    repo: "docker://quay.io/wtsicgp/dockstore-cgpwgs:2.1.1"
  caveman:
    sif: "resources/containers/caveman153.sif"
    repo: "docker://quay.io/wtsicgp/cgpcavemanwrapper:1.15.3"
  brass:
    sif: "resources/containers/brass634.sif"
    repo: "docker://quay.io/wtsicgp/brass:v6.3.4"
  freec:
    sif: "resources/containers/control-freec-11.6.sif"
    repo: "docker://quay.io/biocontainers/control-freec:11.6b--h503566f_2"
    config_wes: "workflow/WES/scripts/freec/config_exome.ini"
  facets:
    sif: "resources/containers/facets-suite-208.sif"
    repo: "docker://asntech/facets-suite:v2.0.8"
  igcaller:
    sif: "resources/containers/igcaller-1.2.1.simg"
    repo: "docker://shahcompbio/igcaller:latest"
  delly:
    sif: "resources/containers/delly_v1.7.2.sif"
    repo: "docker://dellytools/delly:latest"
  jasmine:
    sif: "resources/containers/jasminesv.sif"
    repo: "https://depot.galaxyproject.org/singularity/jasminesv:1.1.5--hdfd78af_0"
  svaba:
    sif: "resources/containers/svaba.sif"
    repo: "https://depot.galaxyproject.org/singularity/svaba:1.1.0--hf5e1c6e_5"
  cgpbattenberg:
    sif: "resources/containers/cgpbattenberg371.sif"
    repo: "docker://quay.io/ohsu-comp-bio/battenberg:mar-17"
  arriba:
    sif: "resources/containers/arriba240.sif"
    repo: "docker://uhrigs/arriba:2.4.0"
    call: "/arriba_v2.4.0/arriba "  
  lofreq:
    sif: "resources/containers/lofreq215.sif"
    repo: "https://depot.galaxyproject.org/singularity/lofreq:broken---2.5.1--py38h1bd3507_2"
  muse:
    sif: "resources/containers/muse230.sif"
    repo: "https://depot.galaxyproject.org/singularity/muse:2.1.2--h3b3e331_3"
  deepvariant_somatic:
    sif: "resources/containers/deepvariant_deepsomatic-1.9.0.sif"
    repo: "docker://google/deepsomatic:1.10.0"
  gridss:
    sif: "resources/containers/gridss2_13_2.sif"
    repo: "https://depot.galaxyproject.org/singularity/gridss:2.13.1--h270b39a_0"
  conpair:
    sif: "resources/containers/conpair_latest.sif"
    repo: "docker://quay.io/rsrivas9784/conpair:v3"

  lancet2:
    sif: "resources/containers/lancet2.sif"
    repo: "docker://us-central1-docker.pkg.dev/nygc-app-c-148c/lancet-public/lancet:v2.8.6-main-6b2317c8"

  discvrseq:
    sif: "resources/containers/discvrseq.sif"
    repo: "docker://ghcr.nju.edu.cn/bimberlab/discvrseq:latest"

  ngs_bit:
    sif: "resources/containers/ngs-bit-2025.sif"
    repo: "https://depot.galaxyproject.org/singularity/ngs-bits%3A2025_12--py314h40a1aea_0"

  qualimap:
    sif: "resources/containers/qualimap.sif"
    repo: "https://depot.galaxyproject.org/singularity/qualimap:2.3--hdfd78af_0"

  annotsv:
    sif: "resources/containers/annotsv_355.sif"
    repo: "https://depot.galaxyproject.org/singularity/annotsv%3A3.5.8--hdfd78af_1"

  moalmanac:
    sif: "resources/containers/moalmanac_latest.sif"
    repo: "docker://vanallenlab/moalmanac:latest"
  
  octopus:
    sif: "resources/containers/octopus.sif"
    repo: "https://depot.galaxyproject.org/singularity/octopus%3A0.7.4--ha3c1580_2"

  gatk4:
    sif: "resources/containers/gatk4_462.sif"
    repo: "https://depot.galaxyproject.org/singularity/gatk4%3A4.6.2.0--py310hdfd78af_1"

  octopusv:
    sif: "resources/containers/octopusv.sif"
    repo: "https://depot.galaxyproject.org/singularity/octopusv%3A0.3.2--pyhdfd78af_0"

  freebayes:
    sif: "resources/containers/freebayes.sif"
    repo: "https://depot.galaxyproject.org/singularity/freebayes%3A1.3.9--hbefcdb2_3"
  
  vardict_java:
    sif: "resources/containers/vardict_java.sif"
    repo: "https://depot.galaxyproject.org/singularity/vardict-java%3A1.8.3--hdfd78af_0"

  sequenza:
    sif:
    repo: "docker://sequenza/sequenza:3.99rc0"

    



  