softwares:
  sentieon:
    call: "/public/astra/bin/_sentieon/bin/sentieon "

conda:
    clindet_main: 'clindet_main'
    multiqc: 'clindet_main'
    clindet_rsem: 'clindet_rsem'
    clindet_vep: 'clindet_vep'
    facets:
    gsutils: "gsutils"
    hmftools: 'hmftools'
    strelka: 'strelka'
    trust4: 'clindet_rsem'
    rna: 'clindet_rsem'
    clindet_mut: "clindet_mutflag"
    cancer_report:

params:
  java:
    temp_directory: "/public/ClinicalExam/lj_sih/projects/project_pipeline/WES/_tmp"
