##### Modules #####
include: "../common/rules/qc.smk"
include: "../common/rules/mapping.smk"
include: "rules/calling_unpaired.smk"

## cgp pipeline caller
include: "../common/rules/cgp/cgppindel.smk"
include: "../common/rules/cgp/cgpCaVEMan.smk"

## rtm
include: "rules/rtm/paired/SNV.smk"
include: "rules/rtm/paired/CNV.smk"

# post process steps
include: "../common/rules/merge_loop.smk"
include: "../common/rules/merge_loop_germline.smk"
include: "../common/rules/case_report.smk"

## SV call rules
BRASS_CNV = config['singularity']['brass'].get("CNV", 'ASCAT')     
include: "rules/rtm/paired/SV.smk"
include: "rules/report/multiqc.smk"
