project:
  output_dir: 'test'
  genome_version: 'b37'
  sample_sheet: '/public/ClinicalExam/lj_sih/projects/project_clindet/test/cgga_sample_sheet.csv'
run_params:
  somatic_caller_list:
    - HaplotypeCaller
    - strelkasomaticmanta
    - cgppindel
    - caveman
    - muse
    # - deepvariant
    - Mutect2
  stages:
    - conpair
    - report
  germ_caller_list:
    - strelkamanta
    - caveman
  somatic_cnv_list:
    - purple
    - ASCAT
    - facets
    - sequenza
    - freec
    - dryclean
  somatic_sv_list:
    - BRASS
    - delly
    - gridss
    - igcaller
    - linx
    - svaba
    - Manta
  tumor_only_caller:
    - sage
  tumor_only_cnv_caller:
    - freec
  purple_sv: "gridss"