include: "../common/rules/qc.smk"
include: "../common/rules/mapping.smk"

## cgp pipeline caller
include: "../common/rules/cgp/cgppindel.smk"
include: "../common/rules/cgp/cgpCaVEMan.smk"


# rtm pipeline caller
include: "rules/rtm/paired/SNV.smk"
include: "rules/rtm/paired/CNV.smk"

# rtm unpaired caller
include: "rules/rtm/unpaired/SNV.smk"
include: "rules/rtm/unpaired/CNV.smk"

# post process steps
include: "../common/rules/merge_loop.smk"
include: "../common/rules/merge_loop_germline.smk"
include: "../common/rules/mutation_flag.smk"
include: "../common/rules/case_report.smk"
include: "rules/report/multiqc.smk"

# case report
include:'rules/report/case_report.smk'